home:
  path: /
  defaults: { _controller: JwtApp\Infrastructure\Delivery\Http\Controller\DefaultController::indexAction }

api_login_check:
  path: /api/login_check

api_hello:
  path: /api/hello
  defaults: { _controller: JwtApp\Infrastructure\Delivery\Http\Controller\HelloController::hello }
  methods: [GET]
  requirements:
    _format: json
